version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ../server
    command: ["npm", "run", "start:prod"]
    environment:
      DATABASE_URL: postgresql://chatuser:chatpass@postgres:5432/chatdb?schema=public
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: supersecretkey
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ../client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: